name: Ortografia Check README.md

on: [push, pull_request]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spell check
        run: cspell "README.md"
