name: Orthography Check README.md

# Disparar el flujo de trabajo en eventos de push y pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spell-check:
    # Definir la última versión de Ubuntu como el runner
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Instalar cspell globalmente usando npm
      - name: Install cspell and dictionary
        run: |
          npm install -g cspell
          npm install -g @cspell/dict-es-es
          cspell link add @cspell/dict-es-es

      # Paso 3: Ejecutar verificación ortográfica en el archivo README.md
      - name: Run spell check
        run: cspell "README.md" --config cSpell.json
